openapi: 3.0.3

#  This file is part of the eliona project.
#  Copyright © 2022 LEICOM iTEC AG. All Rights Reserved.
#  ______ _ _
# |  ____| (_)
# | |__  | |_  ___  _ __   __ _
# |  __| | | |/ _ \| '_ \ / _` |
# | |____| | | (_) | | | | (_| |
# |______|_|_|\___/|_| |_|\__,_|
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
#  BUT NOT LIMITED  TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#  NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
#  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

info:
  version: 1.0.0
  title: Kentix app API
  description: API to access and configure the Kentix app
externalDocs:
  description: Find out more about the Kentix app
  url: https://github.com/eliona-smart-building-assistant/app-template
servers:
  - url: http://template/v1

tags:
  - name: Configuration
    description: Configure access to Kentix devices
    externalDocs:
      url: https://github.com/eliona-smart-building-assistant/kentix-app

paths:
  /configs:
    get:
      tags:
        - Configuration
      summary: Get all Kentix configurations
      description: Gets information about all Kentix configurations
      operationId: getConfigurations
      responses:
        200:
          description: Successfully returned configured Kentix configurations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Configuration'
    post:
      tags:
        - Configuration
      summary: Creates a Kentix configuration
      description: Creates a Kentix configuration.
      operationId: postConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
      responses:
        201:
          description: Successfully created a new Kentix configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'

components:
  schemas:
    Configuration:
      type: object
      description: Each configuration defines access to one Kentix device.
      properties:
        id:
          type: integer
          format: int64
          description: Internal identifier for the configured device (created automatically). This identifier have to use always if you remove or update existing configured endpoints.
          readOnly: true
          nullable: true
        address:
          type: string
          format: string
          description: IP or hostname of the Kentix device
          example: 10.10.10.101
        apiKey:
          type: string
          description: Kentix API key
        enable:
          type: boolean
          description: Flag to enable or disable the device
          default: true
          nullable: true
        refreshInterval:
          type: integer
          description: Interval in seconds for collecting data from device
          default: 60
        requestTimeout:
          type: integer
          description: Timeout in seconds
          default: 120
          nullable: true
        active:
          type: boolean
          readOnly: true
          description: Set to `true` by the app when running and to `false` when app is stopped
          nullable: true
        projectIDs:
          type: array
          description: List of Eliona project ids for which this device should collect data. For each project id all smart devices are automatically created as an asset in Eliona. The mapping between Eliona is stored as an asset mapping in the Kentix app.
          nullable: true
          items:
            type: string
          example:
            - 42
            - 99

    Sensor:
      type: object
      description: Each sensor represents one asset in Eliona.
      properties:
        projectID:
          type: integer
          description: The project ID this asset is assigned to.
        assetID:
          type: integer
          description: ID of a parent asset which groups all device assets
          nullable: true
        serialNumber:
          type: string
          description: Serial number reported by the Kentix device
